### ISSUE TITLE
Error - specific version of pbr needed?

### ISSUE THREAD

**Issue by hbokh** [major/supernova#77]
Supernova just broke down overhere... Tried another install in a virt. environment, which makes no difference. Seems to be "pbr" related to me:

```
$ supernova lon image-list
[SUPERNOVA] Running nova against lon... 
ERROR (ContextualVersionConflict): (pbr 1.0.1 (/home/hbokh/SUPERNOVA/venv/lib/python2.7/site-packages), Requirement.parse('pbr!=0.7,<1.0,>=0.6'), set(['oslo.i18n', 'oslo.config', 'stevedore', 'oslo.serialization', 'oslo.utils']))
```

**NOTE** I don't think this is specific to `supernova`, since `nova` suffers from the same issue.

**Comment by major** [comment]
This has been a thorn in my side over time. :(  Long story short, it's not due to supernova or anything that supernova can control.

To fix it, I normally do this:

    pip uninstall pbr
    pip install python-keystoneclient

You should be left with a working version of pbr after those steps.  Some OpenStack packages set different required versions of pbr and this causes problems like the ones you're seeing.

**Comment by hbokh** [comment]
Thanks, but I'm sorry to say, but the above did not work. This did in a way (with lots of `urllib3` warnings):

`pip install pbr==0.11.0`
